# gRPC 反向代理
server {
    listen 443 ssl;
    http2 on;
    server_name grpc.DOMAIN;

    include /etc/nginx/snippets/ssl.conf;

    location / {
        grpc_pass grpc://host.docker.internal:50051;
        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
        client_max_body_size 0;
    }
}
